version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
